version: '3'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/DockerData/portainer:/data
    deploy:
      placement:
        constraints: [node.role == manager]

  visual:
    image: manomarks/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:8080
    deploy:
      placement:
        constraints: [node.role == manager]

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /mnt/DockerData/registry:/var/lib/registry
      - /mnt/DockerData/certs:/certs
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    user: 1000:1000
